// pr8_react/src/components/BackToTop.tsx
import React, { useEffect, useState } from 'react';

export const BackToTop: React.FC = () => {
  const [show, setShow] = useState(false);

  useEffect(() => {
    const handleScroll = () => {
      setShow(window.scrollY > 300);
    };
    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <button 
      className={`back-to-top ${show ? 'show' : ''}`} 
      type="button" 
      onClick={scrollToTop}
    >
      ↑
    </button>
  );
};

// pr8_vue/src/components/BackToTop.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';

const show = ref(false);

const handleScroll = () => {
  show.value = window.scrollY > 300;
};

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: 'smooth' });
};

onMounted(() => window.addEventListener('scroll', handleScroll));
onUnmounted(() => window.removeEventListener('scroll', handleScroll));
</script>

<template>
  <button 
    class="back-to-top"
    :class="{ show }"
    type="button" 
    @click="scrollToTop"
  >
    ↑
  </button>
</template>
