// pr8_react/src/components/Navbar.tsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { useSiteState } from '../context/SiteContext';

export const Navbar: React.FC = () => {
  const { lang, texts, toggleTheme, setLanguage } = useSiteState();

  return (
    <nav className="main-nav">
      <div className="container nav-row">
        <div className="nav-links">
          <a href="../../index.html">Список робіт</a>
          <NavLink to="/" className={({ isActive }) => (isActive ? 'active' : '')}>
            {texts.navHome}
          </NavLink>
          <NavLink to="/contacts" className={({ isActive }) => (isActive ? 'active' : '')}>
            {texts.navContacts}
          </NavLink>
        </div>

        <div className="nav-controls">
          <button 
            type="button" 
            className={lang === 'uk' ? 'active' : ''} 
            onClick={() => setLanguage('uk')}
          >
            UA
          </button>
          <button 
            type="button" 
            className={lang === 'en' ? 'active' : ''} 
            onClick={() => setLanguage('en')}
          >
            EN
          </button>
          <button type="button" onClick={toggleTheme}>
            {texts.themeButton}
          </button>
        </div>
      </div>
    </nav>
  );
};

// pr8_vue/src/components/Navbar.vue
<script setup lang="ts">
import { useSiteState } from '../composables/useSiteState';

const { lang, texts, toggleTheme, setLanguage } = useSiteState();
</script>

<template>
  <nav class="main-nav">
    <div class="container nav-row">
      <div class="nav-links">
        <a href="../../index.html">Список робіт</a>
        <router-link to="/" exact-active-class="active">{{ texts.navHome }}</router-link>
        <router-link to="/contacts" exact-active-class="active">{{ texts.navContacts }}</router-link>
      </div>

      <div class="nav-controls">
        <button 
          type="button" 
          :class="{ active: lang === 'uk' }" 
          @click="setLanguage('uk')"
        >
          UA
        </button>
        <button 
          type="button" 
          :class="{ active: lang === 'en' }" 
          @click="setLanguage('en')"
        >
          EN
        </button>
        <button type="button" @click="toggleTheme">
          {{ texts.themeButton }}
        </button>
      </div>
    </div>
  </nav>
</template>
