// pr8_react/src/components/ProjectModal.tsx
import React, { useEffect } from 'react';
import { useSiteState } from '../context/SiteContext';
import type { Project } from '../data/translations';

interface ProjectModalProps {
  project: Project | null;
  onClose: () => void;
}

export const ProjectModal: React.FC<ProjectModalProps> = ({ project, onClose }) => {
  const { texts } = useSiteState();

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [onClose]);

  if (!project) return null;

  return (
    <div className="modal open">
      <div className="modal__overlay" onClick={onClose}></div>
      <div className="modal__content">
        <button className="modal__close" type="button" onClick={onClose}>×</button>
        <h3>{project.title}</h3>
        <p>{project.description}</p>
        <p>{project.details}</p>
        <p>
          <a href="https://github.com/" target="_blank" rel="noopener noreferrer">
            {texts.repoLink}
          </a>
        </p>
      </div>
    </div>
  );
};

// pr8_vue/src/components/ProjectModal.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { useSiteState } from '../composables/useSiteState';
import type { Project } from '../data/translations';

const props = defineProps<{ project?: Project | null }>();
const emit = defineEmits<{ (e: 'close'): void }>();

const { texts } = useSiteState();

const handleKeydown = (e: KeyboardEvent) => {
  if (e.key === 'Escape') {
    emit('close');
  }
};

onMounted(() => window.addEventListener('keydown', handleKeydown));
onUnmounted(() => window.removeEventListener('keydown', handleKeydown));
</script>

<template>
  <div v-if="props.project" class="modal open">
    <div class="modal__overlay" @click="emit('close')"></div>
    <div class="modal__content">
      <button class="modal__close" type="button" @click="emit('close')">×</button>
      <h3>{{ props.project.title }}</h3>
      <p>{{ props.project.description }}</p>
      <p>{{ props.project.details }}</p>
      <p>
        <a href="https://github.com/" target="_blank" rel="noopener noreferrer">
          {{ texts.repoLink }}
        </a>
      </p>
    </div>
  </div>
</template>
