// pr8_vue/src/components/Footer.vue
<script setup lang="ts">
import { useRoute } from 'vue-router';
import { useSiteState } from '../composables/useSiteState';
import { computed } from 'vue';

const { texts } = useSiteState();
const route = useRoute();
const isHome = computed(() => route.path === '/');
</script>

<template>
  <footer>
    <div class="container footer-row">
      <p>{{ texts.footerText }}</p>
      <router-link v-if="isHome" to="/contacts">{{ texts.footerContacts }}</router-link>
      <router-link v-else to="/">{{ texts.backHome }}</router-link>
    </div>
  </footer>
</template>

// pr8_react/src/components/Footer.tsx
import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import { useSiteState } from '../context/SiteContext';

export const Footer: React.FC = () => {
  const { texts } = useSiteState();
  const location = useLocation();

  return (
    <footer>
      <div className="container footer-row">
        <p>{texts.footerText}</p>
        {location.pathname === '/' ? (
          <Link to="/contacts">{texts.footerContacts}</Link>
        ) : (
          <Link to="/">{texts.backHome}</Link>
        )}
      </div>
    </footer>
  );
};
