// pr8_angular/src/app/pages/home/home.component.ts
import { CommonModule } from '@angular/common';
import { Component, computed, effect, HostListener, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { Title } from '@angular/platform-browser';
import { ProjectItem } from '../../data/translations';
import { SiteStateService } from '../../services/site-state.service';

@Component({
  selector: 'app-home-page',
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './home.component.html'
})
export class HomeComponent {
  readonly site = inject(SiteStateService);
  private readonly title = inject(Title);

  readonly selectedTag = signal('all');
  readonly openedProjectId = signal<number | null>(null);
  readonly showBackToTop = signal(false);

  readonly allTags = computed(() => {
    const tags = new Set<string>();
    for (const project of this.site.texts().projects) {
      for (const tag of project.tags) {
        tags.add(tag);
      }
    }

    return ['all', ...Array.from(tags)];
  });

  readonly visibleProjects = computed(() => {
    const currentTag = this.selectedTag();
    const projects = this.site.texts().projects;
    if (currentTag === 'all') {
      return projects;
    }

    return projects.filter((project) => project.tags.includes(currentTag));
  });

  readonly modalProject = computed(() => {
    const id = this.openedProjectId();
    if (id === null) return null;
    return this.site.texts().projects.find((project) => project.id === id) ?? null;
  });

  constructor() {
    effect(() => {
      this.title.setTitle(this.site.pageTitle('index'));
    });
  }

  setLanguage(lang: 'uk' | 'en'): void {
    this.site.setLanguage(lang);
  }

  toggleTheme(): void {
    this.site.toggleTheme();
  }

  setTag(tag: string): void {
    this.selectedTag.set(tag);
  }

  openModal(project: ProjectItem): void {
    this.openedProjectId.set(project.id);
  }

  closeModal(): void {
    this.openedProjectId.set(null);
  }

  scrollToTop(): void {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  @HostListener('window:scroll')
  onWindowScroll(): void {
    this.showBackToTop.set(window.scrollY > 300);
  }

  @HostListener('window:keydown', ['$event'])
  onWindowKeydown(event: KeyboardEvent): void {
    if (event.key === 'Escape') {
      this.closeModal();
    }
  }
}

<header class="hero">
  <div class="container">
    <p class="hero__label">ПРАКТИЧНА РОБОТА №8</p>
    <h1>{{ site.texts().heroTitle }}</h1>
    <p>
      {{ site.texts().heroText }}
    </p>
    <div class="hero__actions">
      <a class="btn-link" href="#projects">{{ site.texts().projectsLink }}</a>
    </div>
  </div>
</header>

<nav class="main-nav">
  <div class="container nav-row">
    <div class="nav-links">
      <a href="../../../../index.html">Список робіт</a>
      <a
        routerLink="/"
        routerLinkActive="active"
        [routerLinkActiveOptions]="{ exact: true }"
      >
        {{ site.texts().navHome }}
      </a>
      <a routerLink="/contacts" routerLinkActive="active">{{ site.texts().navContacts }}</a>
    </div>

    <div class="nav-controls">
      <button
        id="langUk"
        type="button"
        [class.active]="site.lang() === 'uk'"
        (click)="setLanguage('uk')"
      >
        UA
      </button>
      <button
        id="langEn"
        type="button"
        [class.active]="site.lang() === 'en'"
        (click)="setLanguage('en')"
      >
        EN
      </button>
      <button id="themeToggle" type="button" (click)="toggleTheme()">{{ site.texts().themeButton }}</button>
    </div>
  </div>
</nav>

<main>
  <section class="section">
    <div class="container">
      <h2>{{ site.texts().aboutTitle }}</h2>
      <p>{{ site.texts().aboutText }}</p>
    </div>
  </section>

  <section class="section section--alt" id="projects">
    <div class="container">
      <h2>{{ site.texts().projectsTitle }}</h2>

      <div class="controls">
        <p><span>{{ site.texts().shownLabel }}</span> <span>{{ visibleProjects().length }} / {{ site.texts().projects.length }}</span></p>
        <div class="tag-list">
          @for (tag of allTags(); track tag) {
            <button
              type="button"
              class="tag-button"
              [class.active]="selectedTag() === tag"
              (click)="setTag(tag)"
            >
              {{ tag === 'all' ? site.texts().allTag : tag }}
            </button>
          }
        </div>
      </div>

      <div class="project-grid">
        @for (project of visibleProjects(); track project.id) {
          <article class="project-card">
            <h3>{{ project.title }}</h3>
            <p>{{ project.description }}</p>

            <div class="project-tags">
              @for (tag of project.tags; track tag) {
                <span class="project-tag">{{ tag }}</span>
              }
            </div>

            <div class="project-actions">
              <button type="button" (click)="openModal(project)">{{ site.texts().detailsButton }}</button>
            </div>
          </article>
        }
      </div>
    </div>
  </section>
</main>

<footer>
  <div class="container footer-row">
    <p>{{ site.texts().footerText }}</p>
    <a routerLink="/contacts">{{ site.texts().footerContacts }}</a>
  </div>
</footer>

<button id="backToTop" class="back-to-top" type="button" [class.show]="showBackToTop()" (click)="scrollToTop()">↑</button>

<div class="modal" [class.open]="modalProject() !== null">
  <div class="modal__overlay" (click)="closeModal()"></div>
  <div class="modal__content">
    <button class="modal__close" type="button" (click)="closeModal()">×</button>
    @if (modalProject(); as project) {
      <h3>{{ project.title }}</h3>
      <p>{{ project.description }}</p>
      <p>{{ project.details }}</p>
      <p>
        <a href="https://github.com/" target="_blank" rel="noopener noreferrer">{{ site.texts().repoLink }}</a>
      </p>
    }
  </div>
</div>

// pr8_vue/src/pages/Home.vue
<script setup lang="ts">
import { ref, computed, watchEffect } from 'vue';
import { useSiteState } from '../composables/useSiteState';
import type { Project } from '../data/translations';
import ProjectCard from '../components/ProjectCard.vue';
import ProjectModal from '../components/ProjectModal.vue';

const { texts, pageTitle } = useSiteState();
const projects = computed<Project[]>(() => texts.value.projects);

const selectedTag = ref('all');
const modalProject = ref<Project | null>(null);

const tags = computed(() => {
  const allTags = new Set<string>();
  projects.value.forEach(p => p.tags.forEach(t => allTags.add(t)));
  return ['all', ...Array.from(allTags)];
});

const filteredProjects = computed(() => {
  if (selectedTag.value === 'all') return projects.value;
  return projects.value.filter(p => p.tags.includes(selectedTag.value));
});

watchEffect(() => {
  document.title = pageTitle('index');
});
</script>

<template>
  <main>
    <header class="hero">
      <div class="container">
        <p class="hero__label">ПРАКТИЧНА РОБОТА №8</p>
        <h1>{{ texts.heroTitle }}</h1>
        <p>{{ texts.heroText }}</p>
        <div class="hero__actions">
          <a class="btn-link" href="#projects">{{ texts.projectsLink }}</a>
        </div>
      </div>
    </header>

    <section class="section">
      <div class="container">
        <h2>{{ texts.aboutTitle }}</h2>
        <p>{{ texts.aboutText }}</p>
      </div>
    </section>

    <section class="section section--alt" id="projects">
      <div class="container">
        <h2>{{ texts.projectsTitle }}</h2>
        <div class="controls">
          <p>
            <span>{{ texts.shownLabel }}</span> 
            <span>{{ filteredProjects.length }} / {{ projects.length }}</span>
          </p>
          <div class="tag-list">
            <button 
              v-for="tag in tags" 
              :key="tag"
              type="button" 
              class="tag-button"
              :class="{ active: selectedTag === tag }"
              @click="selectedTag = tag"
            >
              {{ tag === 'all' ? texts.allTag : tag }}
            </button>
          </div>
        </div>

        <div class="project-grid">
          <ProjectCard 
            v-for="project in filteredProjects" 
            :key="project.id" 
            :project="project" 
            @open-details="id => modalProject = projects.find(p => p.id === id) || null" 
          />
        </div>
      </div>
    </section>

    <ProjectModal :project="modalProject" @close="modalProject = null" />
  </main>
</template>
