// pr8_vue/src/pages/Contacts.vue
<script setup lang="ts">
import { watchEffect } from 'vue';
import { useSiteState } from '../composables/useSiteState';

const { texts, pageTitle } = useSiteState();

watchEffect(() => {
  document.title = pageTitle('contacts');
});
</script>

<template>
  <main>
    <header class="hero">
      <div class="container">
        <p class="hero__label">ПРАКТИЧНА РОБОТА №8</p>
        <h1>{{ texts.contactsTitle }}</h1>
        <p>{{ texts.contactsText }}</p>
        <div class="hero__actions">
          <router-link class="btn-link" to="/">На головну</router-link>
        </div>
      </div>
    </header>

    <section class="section">
      <div class="container">
        <div class="card">
          <h2>{{ texts.contactsListTitle }}</h2>
          <p><strong>Email:</strong> <a href="mailto:illia.student@email.com">illia.student@email.com</a></p>
          <p><strong>GitHub:</strong> <a href="https://github.com/" target="_blank" rel="noopener noreferrer">github.com/illia</a></p>
          <p><strong>Telegram:</strong> <a href="https://t.me/" target="_blank" rel="noopener noreferrer">@illia</a></p>
        </div>
      </div>
    </section>
  </main>
</template>

// pr9/src/app/pages/contacts/contacts.component.ts
import { CommonModule } from '@angular/common';
import { Component, effect, HostListener, inject, signal } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { Title } from '@angular/platform-browser';
import { SiteStateService } from '../../services/site-state.service';

@Component({
  selector: 'app-contacts-page',
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './contacts.component.html'
})
export class ContactsComponent {
  readonly site = inject(SiteStateService);
  private readonly title = inject(Title);

  readonly showBackToTop = signal(false);
  readonly menuOpen = signal(false);

  toggleMenu(): void {
    this.menuOpen.update(v => !v);
  }

  closeMenu(): void {
    this.menuOpen.set(false);
  }

  constructor() {
    effect(() => {
      this.title.setTitle(this.site.pageTitle('contacts'));
    });
  }

  setLanguage(lang: 'uk' | 'en'): void {
    this.site.setLanguage(lang);
  }

  toggleTheme(): void {
    this.site.toggleTheme();
  }

  scrollToTop(): void {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  @HostListener('window:scroll')
  onWindowScroll(): void {
    this.showBackToTop.set(window.scrollY > 300);
  }
}

<header class="hero">
  <div class="container">
    <p class="hero__label">ПРАКТИЧНА РОБОТА №8</p>
    <h1>{{ site.texts().contactsTitle }}</h1>
    <p>{{ site.texts().contactsText }}</p>
  </div>
</header>

<nav class="main-nav">
  <div class="container nav-row">
    <button class="burger" type="button" (click)="toggleMenu()" [attr.aria-expanded]="menuOpen()">
      <span></span><span></span><span></span>
    </button>

    <div class="nav-menu" [class.open]="menuOpen()">
      <div class="nav-links">
        <a href="../../../../index.html" (click)="closeMenu()">Список робіт</a>
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }" (click)="closeMenu()">{{ site.texts().navHome }}</a>
        <a routerLink="/contacts" routerLinkActive="active" (click)="closeMenu()">{{ site.texts().navContacts }}</a>
      </div>

      <div class="nav-controls">
        <button id="langUk" type="button" [class.active]="site.lang() === 'uk'" (click)="setLanguage('uk')">UA</button>
        <button id="langEn" type="button" [class.active]="site.lang() === 'en'" (click)="setLanguage('en')">EN</button>
        <button id="themeToggle" type="button" (click)="toggleTheme()">{{ site.texts().themeButton }}</button>
      </div>
    </div>
  </div>
</nav>

<main>
  <section class="section">
    <div class="container">
      <div class="card">
        <h2>{{ site.texts().contactsListTitle }}</h2>
        <p><strong>Email:</strong> <a href="mailto:illia.student@email.com">illia.student@email.com</a></p>
        <p><strong>GitHub:</strong> <a href="https://github.com/" target="_blank" rel="noopener noreferrer">github.com/illia</a></p>
        <p><strong>Telegram:</strong> <a href="https://t.me/" target="_blank" rel="noopener noreferrer">@illia</a></p>
      </div>
    </div>
  </section>
</main>

<footer>
  <div class="container footer-row">
    <p>{{ site.texts().footerText }}</p>
    <a routerLink="/">{{ site.texts().backHome }}</a>
  </div>
</footer>

<button id="backToTop" class="back-to-top" type="button" [class.show]="showBackToTop()" (click)="scrollToTop()">↑</button>
